import { Button, Container, Navbar } from 'react-bootstrap'
import { Link, useNavigate } from 'react-router'
import useUser from '@/hooks/useUser'
import '@/components/layout/Header/Header.css'
import '@/styles/shared/Button.css'
import logoImage from '@/assets/last_race_logo.png'
import { STRINGS } from '@/constants/strings.js'

export function Header() {
  const { user } = useUser()

  return (
    <Navbar className="custom-navbar grainy" expand="lg" sticky="top">
      <Container>
        <Navbar.Brand as={Link} to="/">
          <img
            alt="Last Race logo"
            src={logoImage}
            className="navbar-logo"
          />
        </Navbar.Brand>

        {user ? <UserInfo name={user.username} /> : <LoginButton />}
      </Container>
    </Navbar>
  )
}

function LoginButton() {
  return (
    <Button as={Link} to="/login" className="btn-arcade-login">
      {STRINGS.header.login}
    </Button>
  )
}

function LogoutButton() {
  const navigate = useNavigate()
  const { logout } = useUser()

  return (
    <Button
      className="btn-arcade-secondary btn-arcade-sm d-flex align-items-center gap-2"
      onClick={() => {
        logout()
        navigate('/')
      }}
    > {/* svg generated by gemini */}
      <svg width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
        <path fillRule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
      </svg>
      {STRINGS.header.logout}
    </Button>
  )
}

function UserInfo({ name }) {
  return (
    <div className="d-flex align-items-center gap-3">
      <Link 
        to="/home" 
        className="text-decoration-none text-reset d-flex align-items-center gap-2 user-link-wrapper"
        style={{ transition: 'opacity 0.2s', cursor: 'pointer' }}
        onMouseEnter={(e) => e.currentTarget.style.opacity = '0.7'}
        onMouseLeave={(e) => e.currentTarget.style.opacity = '1'}
      > {/* svg generated by gemini */}
        <svg 
          width="20" 
          height="20" 
          fill="currentColor" 
          className="text-info" 
          viewBox="0 0 16 16"
          style={{ filter: 'drop-shadow(0 0 4px rgba(0, 209, 255, 0.4))' }}
        >
          <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
          <path fillRule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
        </svg>

        <span className="user-greeting fw-bold m-0">
          {name.toUpperCase()}
        </span>
      </Link>

      <LogoutButton />
    </div>
  )
}